<html>
<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />

</head>
<body>
<div align ="center">
<h1 align="center">CREATE A USER</H1>
<form name="ekleform" method="post" action="uyeklebaglan.php">
ADI:<input type="text" name="adiniz" value="" size="40" /><br/><br/>
SOYADI:<input type="text" name="soyadi" value="" size="40"/><br/><br/>
SİFRE:<input type="text" name="sifre" value="" size="40" /><br/><br/>
E-POSTA:<input type="text" name="eposta" value="" size="40" /><br/><br/>
<input type="submit" name="submit">
</form>
</div>
</body>
</html>